version: '3.8'
services:
  openmusic:
    build: .
    container_name: openmusic
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
